jobs:
  build:
    continue-on-error: true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@v3
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Download Eclipse on Ubuntu
      run: 'curl -L ''https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.24-202206070700/eclipse-SDK-4.24-linux-gtk-x86_64.tar.gz&mirror_id=1''
        --output eclipse-SDK-4.24-linux-gtk-x86_64.tar.gz

        tar xzf eclipse-SDK-4.24-linux-gtk-x86_64.tar.gz eclipse

        echo "eclipseRoot.dir=$(pwd)/eclipse" | tee eclipsePlugin/local.properties

        '
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Download Eclipse on Windows
      run: 'curl ''https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.24-202206070700/eclipse-SDK-4.24-win32-x86_64.zip&mirror_id=1''
        -o eclipse-SDK-4.24-win32-x86_64.zip

        Expand-Archive "eclipse-SDK-4.24-win32-x86_64.zip" -DestinationPath "." -Force

        $escapedPwd = $pwd.Path -replace ''\\'', ''\\''

        [System.IO.File]::WriteAllLines("$pwd\\eclipsePlugin\\local.properties", "eclipseRoot.dir=$escapedPwd\\eclipse")

        '
      shell: powershell
    - continue-on-error: true
      if: matrix.os == 'macos-latest'
      name: Download Eclipse on Mac
      run: 'curl -L ''https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.24-202206070700/eclipse-SDK-4.24-macosx-cocoa-x86_64.dmg&mirror_id=1''
        --output eclipse-SDK-4.24-macosx-cocoa-x86_64.dmg

        hdiutil attach eclipse-SDK-4.24-macosx-cocoa-x86_64.dmg

        cp -r /Volumes/Eclipse/Eclipse.app /Applications/

        hdiutil detach /Volumes/Eclipse

        echo "eclipseRoot.dir=/Applications/Eclipse.app" | tee eclipsePlugin/local.properties

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      if: matrix.os != 'windows-latest'
      name: Pre-build setup
      run: "echo \"keystorepass=${KEYSTORE_PASS}\" >> gradle.properties\ngit fetch\
        \ --no-tags https://$GITHUB_TOKEN@github.com/spotbugs/spotbugs.git +refs/heads/master:refs/remotes/origin/master\n\
        if [ \"$GPG_SECRET_PASSPHRASE\" != \"\" ]; then\n  gpg --quiet --batch --yes\
        \ --decrypt --passphrase=\"$GPG_SECRET_PASSPHRASE\" --output spotbugs.jks\
        \ .github/workflows/spotbugs.jks.gpg;\nfi\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      if: matrix.os == 'windows-latest'
      name: Pre-build setup Windows
      run: "echo \"keystorepass=${KEYSTORE_PASS}\" >> gradle.properties\ngit fetch\
        \ --no-tags https://$GITHUB_TOKEN@github.com/spotbugs/spotbugs.git +refs/heads/master:refs/remotes/origin/master\n\
        if ( \"$GPG_SECRET_PASSPHRASE\" -ne \"\" ) {\n  gpg --quiet --batch --yes\
        \ --decrypt --passphrase=\"$GPG_SECRET_PASSPHRASE\" --output spotbugs.jks\
        \ .github/workflows/spotbugs.jks.gpg;\n}\n"
    - continue-on-error: true
      env:
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      if: matrix.java == '21'
      name: Build with Sonar JDK ${{ matrix.java }}, ${{ matrix.os }}
      run: './gradlew spotlessCheck build smoketest ${SONAR_LOGIN:+sonar} --no-daemon
        "-Dsonar.token=$SONAR_LOGIN" --scan

        '
    - continue-on-error: true
      env:
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      if: matrix.java != '21'
      name: Build JDK ${{ matrix.java }}, ${{ matrix.os }}
      run: './gradlew spotlessCheck build smoketest --no-daemon --scan

        '
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        - macos-14
      max-parallel: 6
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
