jobs:
  stale-pr-and-issue:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: -1
        days-before-stale: 30
        exempt-all-pr-assignees: true
        only-issue-labels: need info
        stale-issue-label: need info
        stale-pr-label: Stale
name: Automated ticket management
on:
  repository_dispatch:
    types: trigger-ga___ticket-management.yml
permissions:
  issues: write
  pull-requests: write
